<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_D6a_oODtEeydTb8Jw5-_uA" name="faturacao" author="danis" bonitaVersion="7.14.0" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_D6t6kODtEeydTb8Jw5-_uA" name="validacao fatura cliente">
      <elements xmi:type="process:Lane" xmi:id="_D63rkODtEeydTb8Jw5-_uA" name="Comercial" actor="_qpO3EOHPEeyyCuc_HDjyTw">
        <elements xmi:type="process:StartEvent" xmi:id="_D7BckODtEeydTb8Jw5-_uA" name="Validação de fatura requisitada" outgoing="_D9aCPODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D7BckuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D7BckeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D7Bck-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_D7KmgODtEeydTb8Jw5-_uA" name="Validar fatura" outgoing="_D9aCNODtEeydTb8Jw5-_uA" incoming="_D9aCPODtEeydTb8Jw5-_uA" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D7KmguDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D7KmgeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D7Kmg-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_FxAAEOS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FxAAEeS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FxAAEuS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FxAAE-S5EeyGi7mpJIpZmA" name="faturaInput.nrHoras" content="faturaInput?.nrHoras" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FxAAFOS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FxAAFeS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setNrHoras">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FxAAFuS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FxAAF-S5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FxAAGOS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FxAAGeS5EeyGi7mpJIpZmA" name="faturaInput.is_validado" content="faturaInput?.is_validado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FxAAGuS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FxAAG-S5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_validado">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FxAAHOS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FxAAHeS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FxAAHuS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FxAAH-S5EeyGi7mpJIpZmA" name="faturaInput.is_aceite" content="faturaInput?.is_aceite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FxAAIOS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FxAAIeS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_aceite">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FxAAIuS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FxAAI-S5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FxAAJOS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FxAAJeS5EeyGi7mpJIpZmA" name="faturaInput.is_desuporte" content="faturaInput?.is_desuporte" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FxAAJuS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FxAAJ-S5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_desuporte">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FxAAKOS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FxAAKeS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FxAAKuS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FxAAK-S5EeyGi7mpJIpZmA" name="faturaInput.is_validadesuporte" content="faturaInput?.is_validadesuporte" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FxAALOS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FxAALeS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_validadesuporte">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_FxAALuS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_FxAAL-S5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_FxAAMOS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_FxAAMeS5EeyGi7mpJIpZmA" name="faturaInput.is_validadeprojeto" content="faturaInput?.is_validadeprojeto" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_FxAAMuS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_FxAAM-S5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_validadeprojeto">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D7KmhODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D7KmheDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D7KmhuDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D7KmiODtEeydTb8Jw5-_uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D7Kmh-DtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_D7KmiuDtEeydTb8Jw5-_uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_D7Kmi-DtEeydTb8Jw5-_uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_D7KmieDtEeydTb8Jw5-_uA">
            <inputs xmi:type="process:ContractInput" xmi:id="_Fw-x8OS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" dataReference="fatura" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Fw-x8eS5EeyGi7mpJIpZmA" name="nrHoras" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Fw-x8uS5EeyGi7mpJIpZmA" name="is_validado" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Fw-x8-S5EeyGi7mpJIpZmA" name="is_aceite" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Fw-x9OS5EeyGi7mpJIpZmA" name="is_desuporte" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Fw-x9eS5EeyGi7mpJIpZmA" name="is_validadesuporte" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Fw-x9uS5EeyGi7mpJIpZmA" name="is_validadeprojeto" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_D7KmjODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_D7KmkODtEeydTb8Jw5-_uA" name="Fatura válida?" outgoing="_D9QRRODtEeydTb8Jw5-_uA _D9jMIODtEeydTb8Jw5-_uA" incoming="_D9aCNODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D7KmkuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D7KmkeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D7Kmk-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_D7UXgODtEeydTb8Jw5-_uA" name="Fatura de projeto ou suporte?" outgoing="_D9jMKODtEeydTb8Jw5-_uA _D9s9IODtEeydTb8Jw5-_uA" incoming="_D9jMIODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D7UXguDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D7UXgeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D7UXg-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_D7dhcODtEeydTb8Jw5-_uA" name="Fatura inválida" incoming="_D9QRRODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D7dhcuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D7dhceDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D7dhc-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_D7dheODtEeydTb8Jw5-_uA" name="Gestor de equipa de suporte" actor="_tKmAkOHPEeyyCuc_HDjyTw">
        <elements xmi:type="process:XORGateway" xmi:id="_D7nScODtEeydTb8Jw5-_uA" name="Fatura  suporte válida?" outgoing="_D92HGODtEeydTb8Jw5-_uA _D9_4EODtEeydTb8Jw5-_uA" incoming="_D9_4GODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D7nScuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D7nSceDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D7nSc-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_D7xDcODtEeydTb8Jw5-_uA" name="Fatura suporte inválida" incoming="_D92HGODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D7xDcuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D7xDceDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D7xDc-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_D76NYODtEeydTb8Jw5-_uA" name="Fatura suporte válida" incoming="_D9_4EODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D76NYuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D76NYeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D76NY-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_D76NaODtEeydTb8Jw5-_uA" name="Validar fatura suporte" outgoing="_D9_4GODtEeydTb8Jw5-_uA" incoming="_D9s9IODtEeydTb8Jw5-_uA" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D76NauDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D76NaeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D76Na-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Ho25kOS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ho25keS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ho25kuS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ho25k-S5EeyGi7mpJIpZmA" name="faturaInput.nrHoras" content="faturaInput?.nrHoras" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ho25lOS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ho25leS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setNrHoras">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ho25luS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ho25l-S5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ho25mOS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ho25meS5EeyGi7mpJIpZmA" name="faturaInput.is_validado" content="faturaInput?.is_validado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ho25muS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ho25m-S5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_validado">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ho25nOS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ho25neS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ho25nuS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ho25n-S5EeyGi7mpJIpZmA" name="faturaInput.is_aceite" content="faturaInput?.is_aceite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ho25oOS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ho25oeS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_aceite">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ho25ouS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ho25o-S5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ho25pOS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ho25peS5EeyGi7mpJIpZmA" name="faturaInput.is_desuporte" content="faturaInput?.is_desuporte" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ho25puS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ho25p-S5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_desuporte">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ho25qOS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ho25qeS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ho25quS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ho25q-S5EeyGi7mpJIpZmA" name="faturaInput.is_validadesuporte" content="faturaInput?.is_validadesuporte" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ho25rOS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ho25reS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_validadesuporte">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ho25ruS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ho25r-S5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ho25sOS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ho25seS5EeyGi7mpJIpZmA" name="faturaInput.is_validadeprojeto" content="faturaInput?.is_validadeprojeto" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ho25suS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ho25s-S5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_validadeprojeto">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D76NbODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D76NbeDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D76NbuDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D76NcODtEeydTb8Jw5-_uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D76Nb-DtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_D76NcuDtEeydTb8Jw5-_uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_D76Nc-DtEeydTb8Jw5-_uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_D76NceDtEeydTb8Jw5-_uA">
            <inputs xmi:type="process:ContractInput" xmi:id="_Ho2SgOS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" dataReference="fatura" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Ho2SgeS5EeyGi7mpJIpZmA" name="nrHoras" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ho2SguS5EeyGi7mpJIpZmA" name="is_validado" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ho2Sg-S5EeyGi7mpJIpZmA" name="is_aceite" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ho2ShOS5EeyGi7mpJIpZmA" name="is_desuporte" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ho2SheS5EeyGi7mpJIpZmA" name="is_validadesuporte" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ho2ShuS5EeyGi7mpJIpZmA" name="is_validadeprojeto" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_D76NdODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_D8D-YODtEeydTb8Jw5-_uA" name="Gestor de projeto" actor="_ua05YOHPEeyyCuc_HDjyTw">
        <elements xmi:type="process:XORGateway" xmi:id="_D8NvYODtEeydTb8Jw5-_uA" name="Fatura projeto válida?" outgoing="_D9s9MODtEeydTb8Jw5-_uA _D92HEODtEeydTb8Jw5-_uA" incoming="_D9s9KODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D8NvYuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D8NvYeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D8NvY-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_D8NvaODtEeydTb8Jw5-_uA" name="Fatura projeto inválida" incoming="_D9s9MODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D8NvauDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D8NvaeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D8Nva-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_D8W5VODtEeydTb8Jw5-_uA" name="Fatura projeto valida" incoming="_D92HEODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D8W5VuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D8W5VeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D8W5V-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_D8gqUODtEeydTb8Jw5-_uA" name="Validar fatura projeto" outgoing="_D9s9KODtEeydTb8Jw5-_uA" incoming="_D9jMKODtEeydTb8Jw5-_uA" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D8gqUuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D8gqUeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D8gqU-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Ip6t9-S5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ip6t-OS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ip6t-eS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ip6t-uS5EeyGi7mpJIpZmA" name="faturaInput.nrHoras" content="faturaInput?.nrHoras" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Integer">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ip6t--S5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ip6t_OS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setNrHoras">
              <inputTypes>java.lang.Integer</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ip6t_eS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ip6t_uS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ip6t_-S5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ip6uAOS5EeyGi7mpJIpZmA" name="faturaInput.is_validado" content="faturaInput?.is_validado" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ip6uAeS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ip6uAuS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_validado">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ip6uA-S5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ip6uBOS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ip6uBeS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ip6uBuS5EeyGi7mpJIpZmA" name="faturaInput.is_aceite" content="faturaInput?.is_aceite" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ip6uB-S5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ip6uCOS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_aceite">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ip6uCeS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ip6uCuS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ip6uC-S5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ip6uDOS5EeyGi7mpJIpZmA" name="faturaInput.is_desuporte" content="faturaInput?.is_desuporte" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ip6uDeS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ip6uDuS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_desuporte">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ip6uD-S5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ip6uEOS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ip6uEeS5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ip6uEuS5EeyGi7mpJIpZmA" name="faturaInput.is_validadesuporte" content="faturaInput?.is_validadesuporte" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ip6uE-S5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ip6uFOS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_validadesuporte">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <operations xmi:type="expression:Operation" xmi:id="_Ip6uFeS5EeyGi7mpJIpZmA">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Ip6uFuS5EeyGi7mpJIpZmA" name="fatura" content="fatura" type="TYPE_VARIABLE" returnType="com.company.model.Fatura">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Ip6uF-S5EeyGi7mpJIpZmA" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Ip6uGOS5EeyGi7mpJIpZmA" name="faturaInput.is_validadeprojeto" content="faturaInput?.is_validadeprojeto" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_Ip6uGeS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Ip6uGuS5EeyGi7mpJIpZmA" type="JAVA_METHOD" expression="setIs_validadeprojeto">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D8gqVODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D8gqVeDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D8gqVuDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D8gqWODtEeydTb8Jw5-_uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D8gqV-DtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_D8gqWuDtEeydTb8Jw5-_uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_D8gqW-DtEeydTb8Jw5-_uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_D8gqWeDtEeydTb8Jw5-_uA">
            <inputs xmi:type="process:ContractInput" xmi:id="_Ip6t8OS5EeyGi7mpJIpZmA" name="faturaInput" type="COMPLEX" dataReference="fatura" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_Ip6t8eS5EeyGi7mpJIpZmA" name="nrHoras" type="INTEGER" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ip6t8uS5EeyGi7mpJIpZmA" name="is_validado" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ip6t8-S5EeyGi7mpJIpZmA" name="is_aceite" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ip6t9OS5EeyGi7mpJIpZmA" name="is_desuporte" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ip6t9eS5EeyGi7mpJIpZmA" name="is_validadesuporte" type="BOOLEAN" createMode="false"/>
              <inputs xmi:type="process:ContractInput" xmi:id="_Ip6t9uS5EeyGi7mpJIpZmA" name="is_validadeprojeto" type="BOOLEAN" createMode="false"/>
            </inputs>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_D8gqXODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_M-fWYOHYEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura">
        <defaultValue xmi:type="expression:Expression" xmi:id="_M-fWYeHYEeyyCuc_HDjyTw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_D6t6oODtEeydTb8Jw5-_uA">
        <targetForm xmi:type="expression:Expression" xmi:id="_D6t6oeDtEeydTb8Jw5-_uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_D6t6ouDtEeydTb8Jw5-_uA">
        <targetForm xmi:type="expression:Expression" xmi:id="_D6t6o-DtEeydTb8Jw5-_uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9QRRODtEeydTb8Jw5-_uA" name="Não" target="_D7dhcODtEeydTb8Jw5-_uA" source="_D7KmkODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9QRReDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9QRRuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_validado == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_4xtCEOHZEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9aCNODtEeydTb8Jw5-_uA" target="_D7KmkODtEeydTb8Jw5-_uA" source="_D7KmgODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9aCNeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9aCNuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9aCPODtEeydTb8Jw5-_uA" target="_D7KmgODtEeydTb8Jw5-_uA" source="_D7BckODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9aCPeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9aCPuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9jMIODtEeydTb8Jw5-_uA" target="_D7UXgODtEeydTb8Jw5-_uA" source="_D7KmkODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9jMIeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9jMIuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_validado == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_7T88YOHZEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9jMKODtEeydTb8Jw5-_uA" name="Projeto" target="_D8gqUODtEeydTb8Jw5-_uA" source="_D7UXgODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9jMKeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9jMKuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_desuporte == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_DZfqsOHbEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9s9IODtEeydTb8Jw5-_uA" name="Suporte" target="_D76NaODtEeydTb8Jw5-_uA" source="_D7UXgODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9s9IeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9s9IuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_desuporte == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_BvoJ4OHbEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9s9KODtEeydTb8Jw5-_uA" target="_D8NvYODtEeydTb8Jw5-_uA" source="_D8gqUODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9s9KeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9s9KuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9s9MODtEeydTb8Jw5-_uA" name="Não" target="_D8NvaODtEeydTb8Jw5-_uA" source="_D8NvYODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9s9MeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9s9MuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_validadeprojeto == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_wgkncOHbEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D92HEODtEeydTb8Jw5-_uA" name="Sim" target="_D8W5VODtEeydTb8Jw5-_uA" source="_D8NvYODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D92HEeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D92HEuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_validadeprojeto == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_xuS-0OHbEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D92HGODtEeydTb8Jw5-_uA" name="Não" target="_D7xDcODtEeydTb8Jw5-_uA" source="_D7nScODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D92HGeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D92HGuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_validadesuporte == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_oxgzEOMlEeykce4rWGppfg" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9_4EODtEeydTb8Jw5-_uA" name="Sim" target="_D76NYODtEeydTb8Jw5-_uA" source="_D7nScODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9_4EeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9_4EuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_validadesuporte == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_pvnaEOMlEeykce4rWGppfg" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D9_4GODtEeydTb8Jw5-_uA" target="_D7nScODtEeydTb8Jw5-_uA" source="_D76NaODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D9_4GeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D9_4GuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_qpO3EOHPEeyyCuc_HDjyTw" name="Comercial" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_tKmAkOHPEeyyCuc_HDjyTw" name="Gestor de equipa de suporte"/>
      <actors xmi:type="process:Actor" xmi:id="_ua05YOHPEeyyCuc_HDjyTw" name="Gestor de projeto"/>
      <contract xmi:type="process:Contract" xmi:id="_D6t6pODtEeydTb8Jw5-_uA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D6t6keDtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D6t6kuDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D6t6k-DtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D6t6lODtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D6t6leDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D6t6luDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D6t6l-DtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D6t6mODtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D6t6meDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D6t6muDtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D6t6m-DtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D6t6nODtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D6t6neDtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D6t6nuDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D6t6n-DtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_D8gqYODtEeydTb8Jw5-_uA" name="faturacao">
      <elements xmi:type="process:Lane" xmi:id="_D8p0QODtEeydTb8Jw5-_uA" name="Contabilidade" actor="_vhlGEOHPEeyyCuc_HDjyTw">
        <elements xmi:type="process:StartEvent" xmi:id="_D8p0SeDtEeydTb8Jw5-_uA" name="Existem faturas para passar" outgoing="_D-ve8ODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D8p0S-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D8p0SuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D8p0TODtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:IntermediateCatchTimerEvent" xmi:id="_D8zlSODtEeydTb8Jw5-_uA" name="1º dia de cada mês" outgoing="_D-mVAODtEeydTb8Jw5-_uA" incoming="_D-mVEODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D8zlSuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D8zlSeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D8zlS-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <condition xmi:type="expression:Expression" xmi:id="_l4fSoOHUEeyyCuc_HDjyTw" name="30 Days 00:00:00" content="2592000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_D89WQODtEeydTb8Jw5-_uA" name="(Re)Emitir fatura" outgoing="_D-SzCODtEeydTb8Jw5-_uA" incoming="_D-ckAODtEeydTb8Jw5-_uA _D-ckCODtEeydTb8Jw5-_uA _D-ckEODtEeydTb8Jw5-_uA _D-mVAODtEeydTb8Jw5-_uA" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D89WQuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D89WQeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D89WQ-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D89WRODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D89WReDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D89WRuDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D89WSODtEeydTb8Jw5-_uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D89WR-DtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_D89WSuDtEeydTb8Jw5-_uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_D89WS-DtEeydTb8Jw5-_uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_D89WSeDtEeydTb8Jw5-_uA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_D89WTODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_D89WXuDtEeydTb8Jw5-_uA" name="Fatura validada?" outgoing="_D-JpIODtEeydTb8Jw5-_uA _D-ckCODtEeydTb8Jw5-_uA" incoming="_D-SzAODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D89WYODtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D89WX-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D89WYeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_D9GgMODtEeydTb8Jw5-_uA" name="Fatura mensal enviada" incoming="_D-JpGODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D9GgMuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D9GgMeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D9GgM-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_D9GgOODtEeydTb8Jw5-_uA" name="Enviar fatura ao cliente para aprovação" outgoing="_D-JpEODtEeydTb8Jw5-_uA" incoming="_D-JpIODtEeydTb8Jw5-_uA" overrideActorsOfTheLane="false" priority="1">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D9GgOuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D9GgOeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D9GgO-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D9GgPODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D9GgPeDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D9GgPuDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D9GgQODtEeydTb8Jw5-_uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D9GgP-DtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_D9GgQuDtEeydTb8Jw5-_uA">
            <targetForm xmi:type="expression:Expression" xmi:id="_D9GgQ-DtEeydTb8Jw5-_uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_D9GgQeDtEeydTb8Jw5-_uA"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_D9GgRODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_D9QRMODtEeydTb8Jw5-_uA" name="Fatura aceite pelo cliente?" outgoing="_D-JpGODtEeydTb8Jw5-_uA _D-ckAODtEeydTb8Jw5-_uA" incoming="_D-JpEODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D9QRMuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D9QRMeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D9QRM-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ReceiveTask" xmi:id="_D9QROODtEeydTb8Jw5-_uA" name="Ordem de faturação de projeto" outgoing="_D-ckEODtEeydTb8Jw5-_uA" incoming="_D-mVCODtEeydTb8Jw5-_uA" event="ordemfaturacao">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D9QROuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D9QROeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D9QRO-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D9QRPODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D9QRPeDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D9QRPuDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D9QRQODtEeydTb8Jw5-_uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D9QRP-DtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <correlation xmi:type="expression:TableExpression" xmi:id="_IWhpkOHUEeyyCuc_HDjyTw"/>
        </elements>
        <elements xmi:type="process:InclusiveGateway" xmi:id="_GI8XsOHUEeyyCuc_HDjyTw" name="Gateway_1k0541z" outgoing="_D-mVCODtEeydTb8Jw5-_uA _D-mVEODtEeydTb8Jw5-_uA" incoming="_D-ve8ODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D8zlQuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D8zlQeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D8zlQ-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_1-_msOHVEeyyCuc_HDjyTw" name="Validar fatura de cliente" outgoing="_D-SzAODtEeydTb8Jw5-_uA" incoming="_D-SzCODtEeydTb8Jw5-_uA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D89WUuDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D89WUeDtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D89WU-DtEeydTb8Jw5-_uA" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D89WVuDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D89WV-DtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D89WWODtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D89WWuDtEeydTb8Jw5-_uA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D89WWeDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_1_ANwOHVEeyyCuc_HDjyTw" name="validacao fatura cliente" content="validacao fatura cliente" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_1_ANweHVEeyyCuc_HDjyTw" name="1.0" content="1.0" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_Wo2fsOHUEeyyCuc_HDjyTw" name="projeto" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Projeto">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Wo2fseHUEeyyCuc_HDjyTw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:BusinessObjectData" xmi:id="_en6WEOHWEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Fatura">
        <defaultValue xmi:type="expression:Expression" xmi:id="_en6WEeHWEeyyCuc_HDjyTw" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_D8gqcODtEeydTb8Jw5-_uA">
        <targetForm xmi:type="expression:Expression" xmi:id="_D8gqceDtEeydTb8Jw5-_uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_D8gqcuDtEeydTb8Jw5-_uA">
        <targetForm xmi:type="expression:Expression" xmi:id="_D8gqc-DtEeydTb8Jw5-_uA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-JpEODtEeydTb8Jw5-_uA" target="_D9QRMODtEeydTb8Jw5-_uA" source="_D9GgOODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-JpEeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-JpEuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-JpGODtEeydTb8Jw5-_uA" name="Sim" target="_D9GgMODtEeydTb8Jw5-_uA" source="_D9QRMODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-JpGeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-JpGuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_aceite == true  &amp;&amp; (fatura.is_validadesuporte == true || fatura.is_validadeprojeto == true)" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_8I4HUOHbEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-JpIODtEeydTb8Jw5-_uA" name="Sim" target="_D9GgOODtEeydTb8Jw5-_uA" source="_D89WXuDtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-JpIeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-JpIuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_validado == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_hzux0OHWEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-SzAODtEeydTb8Jw5-_uA" target="_D89WXuDtEeydTb8Jw5-_uA" source="_1-_msOHVEeyyCuc_HDjyTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-SzAeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-SzAuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-SzCODtEeydTb8Jw5-_uA" target="_1-_msOHVEeyyCuc_HDjyTw" source="_D89WQODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-SzCeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-SzCuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-ckAODtEeydTb8Jw5-_uA" name="Não" target="_D89WQODtEeydTb8Jw5-_uA" source="_D9QRMODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-ckAeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-ckAuDtEeydTb8Jw5-_uA" name="newScript()" content="fatura.is_aceite == false" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_DuLeEOHXEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-ckCODtEeydTb8Jw5-_uA" name="Não" target="_D89WQODtEeydTb8Jw5-_uA" source="_D89WXuDtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-ckCeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-ckCuDtEeydTb8Jw5-_uA" name="newScript()" content="!(fatura.is_aceite == true  &amp;&amp; (fatura.is_validadesuporte == true || fatura.is_validadeprojeto == true))" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_OuTxYOHcEeyyCuc_HDjyTw" name="fatura" dataType="_D6a_q-DtEeydTb8Jw5-_uA" className="com.company.model.Faturas"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-ckEODtEeydTb8Jw5-_uA" target="_D89WQODtEeydTb8Jw5-_uA" source="_D9QROODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-ckEeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-ckEuDtEeydTb8Jw5-_uA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-mVAODtEeydTb8Jw5-_uA" target="_D89WQODtEeydTb8Jw5-_uA" source="_D8zlSODtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-mVAeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-mVAuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-mVCODtEeydTb8Jw5-_uA" target="_D9QROODtEeydTb8Jw5-_uA" source="_GI8XsOHUEeyyCuc_HDjyTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-mVCeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-mVCuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-mVEODtEeydTb8Jw5-_uA" name="Fatura de suporte" target="_D8zlSODtEeydTb8Jw5-_uA" source="_GI8XsOHUEeyyCuc_HDjyTw">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-mVEeDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-mVEuDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D-ve8ODtEeydTb8Jw5-_uA" target="_GI8XsOHUEeyyCuc_HDjyTw" source="_D8p0SeDtEeydTb8Jw5-_uA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D-ve8eDtEeydTb8Jw5-_uA"/>
        <condition xmi:type="expression:Expression" xmi:id="_D-ve8uDtEeydTb8Jw5-_uA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_vhlGEOHPEeyyCuc_HDjyTw" name="Contabilidade" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_D8gqdODtEeydTb8Jw5-_uA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D8gqYeDtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D8gqYuDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D8gqY-DtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D8gqZODtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D8gqZeDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D8gqZuDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D8gqZ-DtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D8gqaODtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D8gqaeDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D8gqauDtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D8gqa-DtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D8gqbODtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D8gqbeDtEeydTb8Jw5-_uA">
        <name xmi:type="expression:Expression" xmi:id="_D8gqbuDtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D8gqb-DtEeydTb8Jw5-_uA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_D6a_o-DtEeydTb8Jw5-_uA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_D6a_pODtEeydTb8Jw5-_uA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_D6a_peDtEeydTb8Jw5-_uA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_D6a_puDtEeydTb8Jw5-_uA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_D6a_p-DtEeydTb8Jw5-_uA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_D6a_qODtEeydTb8Jw5-_uA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_D6a_qeDtEeydTb8Jw5-_uA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_D6a_quDtEeydTb8Jw5-_uA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_D6a_q-DtEeydTb8Jw5-_uA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_D6a_oeDtEeydTb8Jw5-_uA" type="Process" element="_D6a_oODtEeydTb8Jw5-_uA" name="Definitions_1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_D8gqdeDtEeydTb8Jw5-_uA" type="2007" element="_D8gqYODtEeydTb8Jw5-_uA">
      <children xmi:type="notation:DecorationNode" xmi:id="_D8gqeuDtEeydTb8Jw5-_uA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_D8gqe-DtEeydTb8Jw5-_uA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_D8p0QeDtEeydTb8Jw5-_uA" type="3007" element="_D8p0QODtEeydTb8Jw5-_uA">
          <children xmi:type="notation:DecorationNode" xmi:id="_D8p0RuDtEeydTb8Jw5-_uA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_D8p0R-DtEeydTb8Jw5-_uA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_D8p0TeDtEeydTb8Jw5-_uA" type="3002" element="_D8p0SeDtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D8p0T-DtEeydTb8Jw5-_uA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D8p0UODtEeydTb8Jw5-_uA" x="-1" y="22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D8p0TuDtEeydTb8Jw5-_uA" x="82" y="147"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D8zlTODtEeydTb8Jw5-_uA" type="3017" element="_D8zlSODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D8zlTuDtEeydTb8Jw5-_uA" type="5032">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D8zlT-DtEeydTb8Jw5-_uA" x="-17" y="13"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D8zlTeDtEeydTb8Jw5-_uA" x="302" y="47"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D89WTeDtEeydTb8Jw5-_uA" type="3005" element="_D89WQODtEeydTb8Jw5-_uA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_D89WT-DtEeydTb8Jw5-_uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D89WTuDtEeydTb8Jw5-_uA" x="410" y="125"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D89WYuDtEeydTb8Jw5-_uA" type="3008" element="_D89WXuDtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D89WZODtEeydTb8Jw5-_uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D89WZeDtEeydTb8Jw5-_uA" x="-15" y="27"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D89WY-DtEeydTb8Jw5-_uA" x="775" y="140"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D9GgNODtEeydTb8Jw5-_uA" type="3003" element="_D9GgMODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D9GgNuDtEeydTb8Jw5-_uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D9GgN-DtEeydTb8Jw5-_uA" x="-17" y="13"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D9GgNeDtEeydTb8Jw5-_uA" x="1312" y="147"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D9GgReDtEeydTb8Jw5-_uA" type="3005" element="_D9GgOODtEeydTb8Jw5-_uA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_D9GgR-DtEeydTb8Jw5-_uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D9GgRuDtEeydTb8Jw5-_uA" x="900" y="125"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D9QRNODtEeydTb8Jw5-_uA" type="3008" element="_D9QRMODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D9QRNuDtEeydTb8Jw5-_uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D9QRN-DtEeydTb8Jw5-_uA" x="15" y="16"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D9QRNeDtEeydTb8Jw5-_uA" x="1065" y="140"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D9QRQeDtEeydTb8Jw5-_uA" type="3026" element="_D9QROODtEeydTb8Jw5-_uA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_D9QRQ-DtEeydTb8Jw5-_uA" type="5012"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D9QRQuDtEeydTb8Jw5-_uA" x="270" y="225"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_GI8-wuHUEeyyCuc_HDjyTw" type="3051" element="_GI8XsOHUEeyyCuc_HDjyTw" fontName=".AppleSystemUIFont">
              <children xmi:type="notation:DecorationNode" xmi:id="_GI8-xOHUEeyyCuc_HDjyTw" visible="false" type="5075">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_GI8-xeHUEeyyCuc_HDjyTw" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_GI8-w-HUEeyyCuc_HDjyTw" x="165" y="140" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1_ANx-HVEeyyCuc_HDjyTw" type="3063" element="_1-_msOHVEeyyCuc_HDjyTw" fontName=".AppleSystemUIFont" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1_ANyeHVEeyyCuc_HDjyTw" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1_ANyOHVEeyyCuc_HDjyTw" x="590" y="125" width="100" height="50"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_D8p0QuDtEeydTb8Jw5-_uA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_D8p0Q-DtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_D8p0RODtEeydTb8Jw5-_uA" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_D8p0SODtEeydTb8Jw5-_uA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D8p0ReDtEeydTb8Jw5-_uA" x="28" y="10" width="1417" height="331"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_D8gqduDtEeydTb8Jw5-_uA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_D8gqd-DtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_D8gqeODtEeydTb8Jw5-_uA" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_D8gqfODtEeydTb8Jw5-_uA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D8gqeeDtEeydTb8Jw5-_uA" width="1445" height="415"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_D6t6peDtEeydTb8Jw5-_uA" type="2007" element="_D6t6kODtEeydTb8Jw5-_uA">
      <children xmi:type="notation:DecorationNode" xmi:id="_D6t6quDtEeydTb8Jw5-_uA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_D6t6q-DtEeydTb8Jw5-_uA" type="7001">
        <children xmi:type="notation:Node" xmi:id="_D63rkeDtEeydTb8Jw5-_uA" type="3007" element="_D63rkODtEeydTb8Jw5-_uA">
          <children xmi:type="notation:DecorationNode" xmi:id="_D63rluDtEeydTb8Jw5-_uA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_D63rl-DtEeydTb8Jw5-_uA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_D7BclODtEeydTb8Jw5-_uA" type="3002" element="_D7BckODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D7BcluDtEeydTb8Jw5-_uA" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D7Bcl-DtEeydTb8Jw5-_uA" x="-14" y="15"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D7BcleDtEeydTb8Jw5-_uA" x="102" y="97"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D7KmjeDtEeydTb8Jw5-_uA" type="3005" element="_D7KmgODtEeydTb8Jw5-_uA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_D7Kmj-DtEeydTb8Jw5-_uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D7KmjuDtEeydTb8Jw5-_uA" x="190" y="75"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D7KmlODtEeydTb8Jw5-_uA" type="3008" element="_D7KmkODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D7KmluDtEeydTb8Jw5-_uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D7Kml-DtEeydTb8Jw5-_uA" x="-10" y="-54"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D7KmleDtEeydTb8Jw5-_uA" x="345" y="90"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D7UXhODtEeydTb8Jw5-_uA" type="3008" element="_D7UXgODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D7UXhuDtEeydTb8Jw5-_uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D7UXh-DtEeydTb8Jw5-_uA" x="-98" y="-19"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D7UXheDtEeydTb8Jw5-_uA" x="345" y="205"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D7dhdODtEeydTb8Jw5-_uA" type="3003" element="_D7dhcODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D7dhduDtEeydTb8Jw5-_uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D7dhd-DtEeydTb8Jw5-_uA" x="-18" y="13"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D7dhdeDtEeydTb8Jw5-_uA" x="798" y="85"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_D63rkuDtEeydTb8Jw5-_uA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_D63rk-DtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_D63rlODtEeydTb8Jw5-_uA" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_D63rmODtEeydTb8Jw5-_uA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D63rleDtEeydTb8Jw5-_uA" x="673" height="275"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_D7dheeDtEeydTb8Jw5-_uA" type="3007" element="_D7dheODtEeydTb8Jw5-_uA">
          <children xmi:type="notation:DecorationNode" xmi:id="_D7dhfuDtEeydTb8Jw5-_uA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_D7dhf-DtEeydTb8Jw5-_uA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_D7nSdODtEeydTb8Jw5-_uA" type="3008" element="_D7nScODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D7nSduDtEeydTb8Jw5-_uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D7nSd-DtEeydTb8Jw5-_uA" x="79" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D7nSdeDtEeydTb8Jw5-_uA" x="601" y="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D7xDdODtEeydTb8Jw5-_uA" type="3003" element="_D7xDcODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D7xDduDtEeydTb8Jw5-_uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D7xDd-DtEeydTb8Jw5-_uA" x="-1" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D7xDdeDtEeydTb8Jw5-_uA" x="798" y="18"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D76NZODtEeydTb8Jw5-_uA" type="3003" element="_D76NYODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D76NZuDtEeydTb8Jw5-_uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D76NZ-DtEeydTb8Jw5-_uA" x="-1" y="23"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D76NZeDtEeydTb8Jw5-_uA" x="798" y="108"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D76NdeDtEeydTb8Jw5-_uA" type="3005" element="_D76NaODtEeydTb8Jw5-_uA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_D76Nd-DtEeydTb8Jw5-_uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D76NduDtEeydTb8Jw5-_uA" x="446" y="48" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_D7dheuDtEeydTb8Jw5-_uA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_D7dhe-DtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_D7dhfODtEeydTb8Jw5-_uA" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_D7dhgODtEeydTb8Jw5-_uA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D7dhfeDtEeydTb8Jw5-_uA" x="53" y="275" width="937" height="257"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_D8D-YeDtEeydTb8Jw5-_uA" type="3007" element="_D8D-YODtEeydTb8Jw5-_uA">
          <children xmi:type="notation:DecorationNode" xmi:id="_D8D-ZuDtEeydTb8Jw5-_uA" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_D8D-Z-DtEeydTb8Jw5-_uA" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_D8NvZODtEeydTb8Jw5-_uA" type="3008" element="_D8NvYODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D8NvZuDtEeydTb8Jw5-_uA" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D8NvZ-DtEeydTb8Jw5-_uA" x="76" y="-22"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D8NvZeDtEeydTb8Jw5-_uA" x="601" y="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D8W5UODtEeydTb8Jw5-_uA" type="3003" element="_D8NvaODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D8W5UuDtEeydTb8Jw5-_uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D8W5U-DtEeydTb8Jw5-_uA" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D8W5UeDtEeydTb8Jw5-_uA" x="798" y="46"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D8W5WODtEeydTb8Jw5-_uA" type="3003" element="_D8W5VODtEeydTb8Jw5-_uA" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_D8W5WuDtEeydTb8Jw5-_uA" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_D8W5W-DtEeydTb8Jw5-_uA" x="-1" y="18"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D8W5WeDtEeydTb8Jw5-_uA" x="798" y="136"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_D8gqXeDtEeydTb8Jw5-_uA" type="3005" element="_D8gqUODtEeydTb8Jw5-_uA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_D8gqX-DtEeydTb8Jw5-_uA" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D8gqXuDtEeydTb8Jw5-_uA" x="446" y="74"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_D8D-YuDtEeydTb8Jw5-_uA"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_D8D-Y-DtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_D8D-ZODtEeydTb8Jw5-_uA" lineColor="12632256"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_D8D-aODtEeydTb8Jw5-_uA"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D8D-ZeDtEeydTb8Jw5-_uA" x="53" y="513" width="937" height="259"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_D6t6puDtEeydTb8Jw5-_uA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_D6t6p-DtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_D6t6qODtEeydTb8Jw5-_uA" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_D6t6rODtEeydTb8Jw5-_uA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D6t6qeDtEeydTb8Jw5-_uA" width="965" height="700"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_D6a_ouDtEeydTb8Jw5-_uA"/>
    <edges xmi:type="notation:Connector" xmi:id="_D9QRR-DtEeydTb8Jw5-_uA" type="4001" element="_D9QRRODtEeydTb8Jw5-_uA" source="_D7KmlODtEeydTb8Jw5-_uA" target="_D7dhdODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9aCMuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9aCM-DtEeydTb8Jw5-_uA" x="-89" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9aCMODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9aCMeDtEeydTb8Jw5-_uA" points="[0, 0, -407, 0]$[407, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9aCN-DtEeydTb8Jw5-_uA" type="4001" element="_D9aCNODtEeydTb8Jw5-_uA" source="_D7KmjeDtEeydTb8Jw5-_uA" target="_D7KmlODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9aCOuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9aCO-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9aCOODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9aCOeDtEeydTb8Jw5-_uA" points="[0, 0, -55, 0]$[55, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9aCP-DtEeydTb8Jw5-_uA" type="4001" element="_D9aCPODtEeydTb8Jw5-_uA" source="_D7BclODtEeydTb8Jw5-_uA" target="_D7KmjeDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9aCQuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9aCQ-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9aCQODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9aCQeDtEeydTb8Jw5-_uA" points="[0, 0, -52, 0]$[52, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9jMI-DtEeydTb8Jw5-_uA" type="4001" element="_D9jMIODtEeydTb8Jw5-_uA" source="_D7KmlODtEeydTb8Jw5-_uA" target="_D7UXhODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9jMJuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9jMJ-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9jMJODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9jMJeDtEeydTb8Jw5-_uA" points="[0, 0, 0, -65]$[0, 65, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9jMK-DtEeydTb8Jw5-_uA" type="4001" element="_D9jMKODtEeydTb8Jw5-_uA" source="_D7UXhODtEeydTb8Jw5-_uA" target="_D8gqXeDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9jMLuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9jML-DtEeydTb8Jw5-_uA" x="6" y="-22"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9jMLODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9jMLeDtEeydTb8Jw5-_uA" points="[0, 0, -80, -125]$[0, 125, -80, 0]$[80, 125, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9s9I-DtEeydTb8Jw5-_uA" type="4001" element="_D9s9IODtEeydTb8Jw5-_uA" source="_D7UXhODtEeydTb8Jw5-_uA" target="_D76NdeDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9s9JuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9s9J-DtEeydTb8Jw5-_uA" x="25" y="-32"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9s9JODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9s9JeDtEeydTb8Jw5-_uA" points="[2, 20, -128, -142]$[2, 161, -128, -1]$[80, 161, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9s9K-DtEeydTb8Jw5-_uA" type="4001" element="_D9s9KODtEeydTb8Jw5-_uA" source="_D8gqXeDtEeydTb8Jw5-_uA" target="_D8NvZODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9s9LuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9s9L-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9s9LODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9s9LeDtEeydTb8Jw5-_uA" points="[0, 0, -55, 0]$[55, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9s9M-DtEeydTb8Jw5-_uA" type="4001" element="_D9s9MODtEeydTb8Jw5-_uA" source="_D8NvZODtEeydTb8Jw5-_uA" target="_D8W5UODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9s9NuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9s9N-DtEeydTb8Jw5-_uA" x="-4" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9s9NODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9s9NeDtEeydTb8Jw5-_uA" points="[0, 0, -172, 25]$[0, -25, -172, 0]$[172, -25, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D92HE-DtEeydTb8Jw5-_uA" type="4001" element="_D92HEODtEeydTb8Jw5-_uA" source="_D8NvZODtEeydTb8Jw5-_uA" target="_D8W5WODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D92HFuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D92HF-DtEeydTb8Jw5-_uA" x="-8" y="3"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D92HFODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D92HFeDtEeydTb8Jw5-_uA" points="[0, 0, -172, -15]$[0, 15, -172, 0]$[172, 15, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D92HG-DtEeydTb8Jw5-_uA" type="4001" element="_D92HGODtEeydTb8Jw5-_uA" source="_D7nSdODtEeydTb8Jw5-_uA" target="_D7xDdODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D92HHuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D92HH-DtEeydTb8Jw5-_uA" x="-4" y="-14"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D92HHODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D92HHeDtEeydTb8Jw5-_uA" points="[0, 0, -172, 25]$[0, -25, -172, 0]$[172, -25, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9_4E-DtEeydTb8Jw5-_uA" type="4001" element="_D9_4EODtEeydTb8Jw5-_uA" source="_D7nSdODtEeydTb8Jw5-_uA" target="_D76NZODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9_4FuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9_4F-DtEeydTb8Jw5-_uA" x="-8" y="3"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9_4FODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9_4FeDtEeydTb8Jw5-_uA" points="[0, 0, -172, -15]$[0, 15, -172, 0]$[172, 15, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D9_4G-DtEeydTb8Jw5-_uA" type="4001" element="_D9_4GODtEeydTb8Jw5-_uA" source="_D76NdeDtEeydTb8Jw5-_uA" target="_D7nSdODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D9_4HuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D9_4H-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D9_4HODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D9_4HeDtEeydTb8Jw5-_uA" points="[0, 0, -55, 0]$[55, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-JpE-DtEeydTb8Jw5-_uA" type="4001" element="_D-JpEODtEeydTb8Jw5-_uA" source="_D9GgReDtEeydTb8Jw5-_uA" target="_D9QRNODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-JpFuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-JpF-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-JpFODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-JpFeDtEeydTb8Jw5-_uA" points="[0, 0, -65, 0]$[65, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-JpG-DtEeydTb8Jw5-_uA" type="4001" element="_D-JpGODtEeydTb8Jw5-_uA" source="_D9QRNODtEeydTb8Jw5-_uA" target="_D9GgNODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-JpHuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-JpH-DtEeydTb8Jw5-_uA" x="-52" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-JpHODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-JpHeDtEeydTb8Jw5-_uA" points="[0, 0, -197, 0]$[197, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-JpI-DtEeydTb8Jw5-_uA" type="4001" element="_D-JpIODtEeydTb8Jw5-_uA" source="_D89WYuDtEeydTb8Jw5-_uA" target="_D9GgReDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-JpJuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-JpJ-DtEeydTb8Jw5-_uA" x="-16" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-JpJODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-JpJeDtEeydTb8Jw5-_uA" points="[0, 0, -75, 0]$[75, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-SzA-DtEeydTb8Jw5-_uA" type="4001" element="_D-SzAODtEeydTb8Jw5-_uA" source="_1_ANx-HVEeyyCuc_HDjyTw" target="_D89WYuDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-SzBuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-SzB-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-SzBODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-SzBeDtEeydTb8Jw5-_uA" points="[0, 0, -85, 0]$[85, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-SzC-DtEeydTb8Jw5-_uA" type="4001" element="_D-SzCODtEeydTb8Jw5-_uA" source="_D89WTeDtEeydTb8Jw5-_uA" target="_1_ANx-HVEeyyCuc_HDjyTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-SzDuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-SzD-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-SzDODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-SzDeDtEeydTb8Jw5-_uA" points="[0, 0, -80, 0]$[80, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-ckA-DtEeydTb8Jw5-_uA" type="4001" element="_D-ckAODtEeydTb8Jw5-_uA" source="_D9QRNODtEeydTb8Jw5-_uA" target="_D89WTeDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-ckBuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-ckB-DtEeydTb8Jw5-_uA" x="-319" y="-49"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-ckBODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-ckBeDtEeydTb8Jw5-_uA" points="[0, 0, 630, 15]$[0, -110, 630, -95]$[-630, -110, 0, -95]$[-630, -15, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-ckC-DtEeydTb8Jw5-_uA" type="4001" element="_D-ckCODtEeydTb8Jw5-_uA" source="_D89WYuDtEeydTb8Jw5-_uA" target="_D89WTeDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-ckDuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-ckD-DtEeydTb8Jw5-_uA" x="15" y="6"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-ckDODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-ckDeDtEeydTb8Jw5-_uA" points="[0, 0, 320, 15]$[0, -75, 320, -60]$[-320, -75, 0, -60]$[-320, -15, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-ckE-DtEeydTb8Jw5-_uA" type="4001" element="_D-ckEODtEeydTb8Jw5-_uA" source="_D9QRQeDtEeydTb8Jw5-_uA" target="_D89WTeDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-ckFuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-ckF-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-ckFODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-ckFeDtEeydTb8Jw5-_uA" points="[50, -1, -90, 99]$[105, -1, -35, 99]$[105, -75, -35, 25]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-mVA-DtEeydTb8Jw5-_uA" type="4001" element="_D-mVAODtEeydTb8Jw5-_uA" source="_D8zlTODtEeydTb8Jw5-_uA" target="_D89WTeDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-mVBuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-mVB-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-mVBODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-mVBeDtEeydTb8Jw5-_uA" points="[0, 0, -102, -60]$[102, 0, 0, -60]$[102, 60, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-mVC-DtEeydTb8Jw5-_uA" type="4001" element="_D-mVCODtEeydTb8Jw5-_uA" source="_GI8-wuHUEeyyCuc_HDjyTw" target="_D9QRQeDtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-mVDuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-mVD-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-mVDODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-mVDeDtEeydTb8Jw5-_uA" points="[0, 0, -80, -75]$[0, 75, -80, 0]$[80, 75, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-mVE-DtEeydTb8Jw5-_uA" type="4001" element="_D-mVEODtEeydTb8Jw5-_uA" source="_GI8-wuHUEeyyCuc_HDjyTw" target="_D8zlTODtEeydTb8Jw5-_uA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-mVFuDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-mVF-DtEeydTb8Jw5-_uA" x="-51" y="-22"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-mVFODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-mVFeDtEeydTb8Jw5-_uA" points="[0, 0, -112, 75]$[0, -75, -112, 0]$[112, -75, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_D-ve8-DtEeydTb8Jw5-_uA" type="4001" element="_D-ve8ODtEeydTb8Jw5-_uA" source="_D8p0TeDtEeydTb8Jw5-_uA" target="_GI8-wuHUEeyyCuc_HDjyTw" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_D-ve9uDtEeydTb8Jw5-_uA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D-ve9-DtEeydTb8Jw5-_uA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D-ve9ODtEeydTb8Jw5-_uA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D-ve9eDtEeydTb8Jw5-_uA" points="[0, 0, -47, 0]$[47, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
